### ISSUE TITLE
Problem with IPTV  channels

### ISSUE THREAD

**Issue by ThierryBourbon** [KavajNaruj/homeassistant-enigma-player#2]
Hi KavajNaruj, Thank you for your works 🥇 , 
When you ask for the service reference of  iptv channel with the subservices function you have :

< e2servicereference>4097:0:1:5555:ABCD:EC:0:0:0:0:http%3a//youriptv.net%3a8000/live/############.ts:CHANNEL< /e2servicereference>

But to zap this reference you must change the  %3a in the adress  in %253a 

GET /api/zap?sRef=4097:0:1:5555:ABCD:EC:0:0:0:0:http%253a//youriptv.net%253a8000/live/############.ts
 
I tried in media_player.py :
await self.request_call('/web/zap?sRef=' + self._sources[source].replace("%3a", "%253a") )
Work fine

**Comment by thierry-rhone** [comment]
Do not mix ikea products with other brands. Each time I tried to add an ikea,  the recognition of new devices no longer works even deleting the share/zigbee2mqtt folder. I returned all of my ikea products. It's a shame because they were really cheap !
